9674886ebe91aa02f9821d83963c5199a35e6e27277c565a0c2adbcea1f877fa
sys_RespNum,int
sys_ElapsedTime,int
sys_SumPageTimes,int
sys_StartTimeStamp,int
sys_EndTimeStamp,int
sys_DataSource,int
sys_RespStatus,int
sys_RespRemoved,bool
sys_DispositionCode,int
sys_LastQuestion,text
sys_UserJavaScript,bool
sys_UserAgent,text
sys_OperatingSystem,text
sys_Browser,text
sys_IPAddress,text
sys_ScreenWidth,int
sys_ShowPrev,bool
sys_CheckSum,int
sys_CAPIDeviceID,text
Q1,int
Q2,int
Q3,int
Q4,int
CBC_Random1,int
CBC_Random2,int
CBC_Random3,int
CBC_Random4,int
CBC_Random5,int
CBC_Random6,int
CBC_Random7,int
CBC_Random8,int
CBC_Random9,int
CBC_Random10,int
CBC_Random11,int
CBC_Random12,int
CBCSwipe_Con1,int
CBCSwipe_Con2,int
CBCSwipe_Con3,int
CBCSwipe_Con4,int
CBCSwipe_Con5,int
CBCSwipe_Con6,int
CBCSwipe_Con7,int
CBCSwipe_Con8,int
CBCSwipe_Con9,int
CBCSwipe_Con10,int
CBCSwipe_Con11,int
CBCSwipe_Con12,int
CBCSwipe_Con13,int
CBCSwipe_Con14,int
CBCSwipe_Con15,int
CBCSwipe_Con16,int
CBCSwipe_Con17,int
CBCSwipe_Con18,int
CBCSwipe_Con19,int
CBCSwipe_Con20,int
CBCSwipe_Con21,int
CBCSwipe_Con22,int
CBCSwipe_Con23,int
CBCSwipe_Con24,int
CBCSwipe_Con25,int
CBCSwipe_Con26,int
CBCSwipe_Con27,int
CBCSwipe_Con28,int
CBCSwipe_Con29,int
CBCSwipe_Con30,int
CBCSwipe_Con31,int
CBCSwipe_Con32,int
CBCSwipe_Con33,int
CBCSwipe_Con34,int
CBCSwipe_Con35,int
CBCSwipe_Con36,int
Gender,int
Age,int
Race_1,bool
Race_2,bool
Race_3,bool
Race_4,bool
Race_5,bool
Race_6,bool
Race_7,bool
Education,int
Income,int
Experience,int
Satisfaction_1,bool
Satisfaction_2,bool
Satisfaction_3,bool
Satisfaction_4,bool
Satisfaction_5,bool
Satisfaction_6,bool
Satisfaction_7,bool
sys_CBCVersion_CBC,int
sys_CBCDesignID_CBC,text
sys_pagetime_1,int
sys_pagetime_2,int
sys_pagetime_3,int
sys_pagetime_4,int
sys_pagetime_5,int
sys_pagetime_6,int
sys_pagetime_7,int
sys_pagetime_8,int
sys_pagetime_9,int
sys_pagetime_10,int
sys_pagetime_11,int
sys_pagetime_12,int
sys_pagetime_13,int
sys_pagetime_14,int
sys_pagetime_15,int
sys_pagetime_16,int
sys_pagetime_17,int
sys_pagetime_18,int
sys_pagetime_19,int
sys_pagetime_20,int
sys_pagetime_21,int
sys_pagetime_22,int
sys_pagetime_23,int
sys_pagetime_24,int
sys_pagetime_25,int
sys_pagetime_26,int
sys_pagetime_27,int
